Nama: Dicky Setiawan

NIM: 22/511229/NPA/19857

Kelas: KOMB


# **Tugas Individu 2 - Pembelajaran Mesin**
Gunakan Car Evaluation dataset berikut: http://archive.ics.uci.edu/ml/datasets/Car+Evaluation

1. Buatlah suatu **model decision tree**  secara manual dengan menggunakan perhitungan **Gini** atau **Entropy** sebagai impurity criterion (Gunakan 15-20 data saja)

2. Implementasikan **classification task** menggunakan **Decision Tree Classifier** dari library sklearn.  Gunakan **GridSearchCV** untuk mendapatkan hyperparameter terbaik.

## **Data Preprocessing**

### **Import Library**

In [ ]:
# Mengimpor library

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import GridSearchCV

### **Data Load**

In [ ]:
# Menghubungkan Google Drive dan Google Colab
from google.colab import drive
drive.mount('/content/gdrive')

# Mengambil dataset
dataset = '/content/gdrive/MyDrive/car.data'
df = pd.read_csv(dataset, header=None)

Mounted at /content/gdrive


Karena dataset memiliki nama kolom yang tidak sesuai, maka dilakukan perubahan terhadap nama kolomnya sebagai berikut:

In [ ]:
# Mengganti nama column/atribut

col_names = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']
df.columns = col_names
col_names

['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']

In [ ]:
# Menampilkan isi dataset secara keseluruhan

df

buying  maint  doors persons lug_boot safety  class
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    low  unacc
4     vhigh  vhigh      2       2      med    med  unacc
...     ...    ...    ...     ...      ...    ...    ...
1723    low    low  5more    more      med    med   good
1724    low    low  5more    more      med   high  vgood
1725    low    low  5more    more      big    low  unacc
1726    low    low  5more    more      big    med   good
1727    low    low  5more    more      big   high  vgood

[1728 rows x 7 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buying    1728 non-null   object
 1   maint     1728 non-null   object
 2   doors     1728 non-null   object
 3   persons   1728 non-null   object
 4   lug_boot  1728 non-null   object
 5   safety    1728 non-null   object
 6   class     1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [ ]:
# Mengecek missing value

df.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
class       0
dtype: int64

### **Exploratory Data Analysis (EDA)**

#### **Eksplorasi Deskriptif Statistik**

In [ ]:
df.describe()

buying  maint doors persons lug_boot safety  class
count    1728   1728  1728    1728     1728   1728   1728
unique      4      4     4       3        3      3      4
top     vhigh  vhigh     2       2    small    low  unacc
freq      432    432   432     576      576    576   1210

#### **Distribusi Frekuensi Nilai**

Untuk mengecek jumlah frekuensi pada variabel yang kategorikal

In [ ]:
col_names = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']
for col in col_names:
    print(df[col].value_counts())   

vhigh    432
high     432
med      432
low      432
Name: buying, dtype: int64
vhigh    432
high     432
med      432
low      432
Name: maint, dtype: int64
2        432
3        432
4        432
5more    432
Name: doors, dtype: int64
2       576
4       576
more    576
Name: persons, dtype: int64
small    576
med      576
big      576
Name: lug_boot, dtype: int64
low     576
med     576
high    576
Name: safety, dtype: int64
unacc    1210
acc       384
good       69
vgood      65
Name: class, dtype: int64


Dapat dilihat bahwa semua kolom dalam dataset merupakan data kategorikal dan kolom "class" merupakan variabel target yang akan digunakan untuk menampilkan hasil evaluasi dari car.data.

In [ ]:
# Mengecek distribusi dari isi kolom "class"

df['class'].value_counts()

unacc    1210
acc       384
good       69
vgood      65
Name: class, dtype: int64

## **Nomor 2**

Implementasikan **classification task** menggunakan **Decision Tree Classifier** dari library sklearn.  Gunakan **GridSearchCV** untuk mendapatkan hyperparameter terbaik.

### **Implementasi classification task menggunakan Decision Tree Classifier**

In [ ]:
# Memberi fitur dari variabel target (class)

X = df.drop('class', axis=1)
y = df['class']
X = pd.get_dummies(X)  # One-hot encoding untuk fitur kategorikal
y = y.map({'unacc': 0, 'acc': 1, 'good': 2, 'vgood': 3})  # Map labels untuk nilai numerik

In [ ]:
# Melakukan split untuk data train dan data test

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Mengecek dimensi data dari X_train and X_test

X_train.shape, X_test.shape

((1382, 21), (346, 21))

#### **Modelling**

In [ ]:
# Membuat model Decision Tree Classifier

dtc = DecisionTreeClassifier(random_state=42)

In [ ]:
# Membuat model Decision Tree Classifier dan mengecek skor akurasi

dtc = DecisionTreeClassifier(
    max_depth = None,
    min_samples_split = 2
)
dtc.fit(X_train, y_train)
y_pred = dtc.predict(X_test)
score = metrics.accuracy_score(y_test, y_pred)
print(score)

0.9624277456647399


In [ ]:
# Membuat confusion matrix

cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix\n\n', cm)

Confusion matrix

 [[235   0   0   0]
 [  3  74   4   2]
 [  0   0  10   1]
 [  0   1   2  14]]


**Classification Report**

Merupakan cara yang digunakan untuk mengevaluasi model dengan menampilkan beberapa indikator seperti skor precision, recall, f1, dan support.

In [ ]:
# Mengecek skor menggunakan classification report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       235
           1       0.99      0.89      0.94        83
           2       0.62      0.91      0.74        11
           3       0.82      0.82      0.82        17

    accuracy                           0.96       346
   macro avg       0.86      0.91      0.87       346
weighted avg       0.97      0.96      0.96       346



### **GridsearchCV untuk mendapatkan hyperparameter terbaik**

In [ ]:
# Membuat dictionary untuk Hyperparameter Tuning
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [3, 5, 7, 10],
    'min_samples_split': [2, 3, 4],
    'min_samples_leaf': [1, 2, 3],
    'max_features': [None, 'sqrt', 'log2']
}

# Membuat GridSearchCV object
grid_search = GridSearchCV(dtc, param_grid=param_grid, cv=5, verbose=2)

# Fitting  GridSearchCV object ke training set
grid_search.fit(X_train, y_train)

# Mendapatkan hyperparameters dan skor terbaik
best_params = grid_search.best_params_
best_score = grid_search.best_score_

# Training decision tree classifier dengan hyperparameter terbaik
best_dtc = DecisionTreeClassifier(**best_params, random_state=42)
best_dtc.fit(X_train, y_train)

# Evaluasi model dengan test set
test_score = best_dtc.score(X_test, y_test)

Fitting 5 folds for each of 216 candidates, totalling 1080 fits
[CV] END criterion=gini, max_depth=3, max_features=None, min_samples_leaf=1, min_samples_split=2; total time=   0.0s
[CV] END criterion=gini, max_depth=3, max_features=None, min_samples_leaf=1, min_samples_split=2; total time=   0.0s
[CV] END criterion=gini, max_depth=3, max_features=None, min_samples_leaf=1, min_samples_split=2; total time=   0.0s
[CV] END criterion=gini, max_depth=3, max_features=None, min_samples_leaf=1, min_samples_split=2; total time=   0.0s
[CV] END criterion=gini, max_depth=3, max_features=None, min_samples_leaf=1, min_samples_split=2; total time=   0.0s
[CV] END criterion=gini, max_depth=3, max_features=None, min_samples_leaf=1, min_samples_split=3; total time=   0.0s
[CV] END criterion=gini, max_depth=3, max_features=None, min_samples_leaf=1, min_samples_split=3; total time=   0.0s
[CV] END criterion=gini, max_depth=3, max_features=None, min_samples_leaf=1, min_samples_split=3; total time=   0.0s


In [ ]:
# Menampilkan hasil

print('Best hyperparameters:', best_params)
print('Best CV score:', best_score)
print('Test score:', test_score)

Best hyperparameters: {'criterion': 'gini', 'max_depth': 10, 'max_features': None, 'min_samples_leaf': 1, 'min_samples_split': 2}
Best CV score: 0.9630879506095328
Test score: 0.9450867052023122
